### ISSUE TITLE
Wrong sorting by name in groups

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-api#220] opened 2018-10-25 09:08 UTC
Hi team,

I just realized that when I'm requesting for the group list to the API ordered by name, I'm getting the results like this:
```
GET /agents/groups
{
  "sort": -name
}
```
Response:

![image](https://user-images.githubusercontent.com/10210567/47489113-1ebfd980-d846-11e8-92b0-151cf1af2755.png)

On the other hand, when I'm requesting for the groups of an agent, I'm getting them ordered correctly:
```
{
  "totalItems": 1,
  "items": [
    {
      "mergedSum": "cf08543b8d048f29879bcb1fe2f44e60",
      "ip": "172.16.1.7",
      "node_name": "node02",
      "status": "Active",
      "configSum": "e7c72a421e0ac1d5737d83a977081e64",
      "group": [
        "default",
        "my_awesome_group.wazuh-1",
        "my_awesome_group.wazuh-2",
        "my_awesome_group.wazuh-3",
        "my_awesome_group.wazuh-4",
        "my_awesome_group.wazuh-5",
        "my_awesome_group.wazuh-6",
        "my_awesome_group.wazuh-7",
        "my_awesome_group.wazuh-8",
        "my_awesome_group.wazuh-9",
        "my_awesome_group.wazuh-10",
        "my_awesome_group.wazuh-11",
....
```

Thanks!

**Comment by mgmacias95** [comment] 2019-02-14 13:36
Hello @manuasir,

Can you give us more detail about your issue? I have tried to reproduce it but I'm getting it correctly sorted:
```javascript
# curl -u foo:bar "localhost:55000/agents/groups?sort=-name&pretty"
{
   "error": 0,
   "data": {
      "items": [
         {
            "count": 0,
            "name": "wazuh.group-101",
            "mergedSum": "8fb2c0285f412a152c9b0ea1abeeb94b",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         {
            "count": 0,
            "name": "wazuh.group-100",
            "mergedSum": "26916c6491677be505df469f73c3bc30",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         {
            "count": 0,
            "name": "wazuh.group-10",
            "mergedSum": "473339bc1532450ad868d8bf9313b763",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         {
            "count": 0,
            "name": "group-101",
            "mergedSum": "a530b3c50c5119c95334db00974a3243",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         {
            "count": 0,
            "name": "group-100",
            "mergedSum": "cc3a297c36bfa8b8ed0bf9aa4032e0f3",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         {
            "count": 0,
            "name": "group-10",
            "mergedSum": "09c2889b0c7b4fff0220e5ad2cc8786c",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         },
         {
            "count": 0,
            "name": "default",
            "mergedSum": "f8d49771911ed9d5c45b03a40babd065",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         }
      ],
      "totalItems": 7
   }
}
```

Best regards,
Marta

**Comment by manuasir** [comment] 2019-02-14 14:04
Hi Marta,

Thanks for the reply, what I meant is the order is not being the same on the two responses, I'm explaining it better here:

Look at the first example, I'm synthesizing the response here as an example:
```
- 10
- 100
- 101
- 11
- 111
- 12
...
```

The order that I'd like to receive should be like this:

```
- 10
- 11
- 12
- 100
- 101
- 111
```
Just like the second response that I've pasted above.

Let me know if you need more details.

Cheers

**Comment by mgmacias95** [comment] 2019-02-15 10:58
Hello @manuasir,

Thanks for clarifying that. 

Just as a note, the groups aren't sorted. They're shown in the exact order they were added to an agent since the order defines priority when merging all groups configurations:
```javascript
# curl -u foo:bar "localhost:55000/agents/001?pretty&select=group"
{
   "error": 0,
   "data": {
      "group": [
         "default",
         "group1",
         "group2",
         "group3",
         "group4",
         "group5",
         "group10",
         "group11",
         "group100",
         "group101",
         "group6"
      ]
   }
}
```

That said, since we're using SQLite to sort the results there isn't much we can do to fix this issue:
```sql
sqlite> .headers on
sqlite> select * from `group` order by name asc;
id|name
1|default
2|group1
7|group10
9|group100
10|group101
8|group11
3|group2
4|group3
5|group4
6|group5
11|group6
```

This is why I'm closing this issue.

Best regards,
Marta

**Closed by mgmacias95** 2019-02-15 10:58 UTC
