### ISSUE TITLE
API wrong experimental path calls encountered end of file

### ISSUE THREAD

**Issue by cristgl** [wazuh/wazuh-api#264] opened 2019-01-08 11:40 UTC
API calls with wrong path at `experimental` show the next message:

```
# curl -u foo:bar -X GET "https://localhost:55000/experimental/sy/?pretty"
curl: (35) Encountered end of file
```

when they should return the next message:
```
"error": 603,
"message": "The requested URL was not found on this server"
```

**Comment by mgmacias95** [comment] 2019-02-14 13:30
Hello @cristgl,

Can you give us more details about this? I tried to reproduce this behaviour having the experimental API calls enabled and disabled:
```shellsession
# grep -i experimental /opt/ossec/api/configuration/config.js
config.experimental_features  = false;
# curl -u foo:bar "localhost:55000/experimental/epepe?pretty"
{
   "error": 603,
   "message": "The requested URL was not found on this server"
}
# sed -i "s:config.experimental_features  = false;:config.experimental_features  = true;:g" /opt/ossec/api/configuration/config.js
# grep -i experimental /opt/ossec/api/configuration/config.js
config.experimental_features  = true;
# systemctl restart wazuh-api
# curl -u foo:bar "localhost:55000/experimental/epepe?pretty"
{
   "error": 603,
   "message": "The requested URL was not found on this server"
}
```

Best regards,
Marta

**Comment by cristgl** [comment] 2019-02-18 10:48
Hello @mgmacias95, I opened the issue testing it on 3.8. Now I have followed your steps at branch 3.9 and I get this results: 

```
# grep -i experimental /var/ossec/api/configuration/config.js 
config.experimental_features  = false;

# curl -u foo:bar "localhost:55000/experimental/epepe?pretty"
curl: (52) Empty reply from server

# sed -i "s:config.experimental_features  = false;:config.experimental_features  = true;:g" /var/ossec/api/configuration/config.js 

# grep -i experimental /var/ossec/api/configuration/config.js
config.experimental_features  = true;

# systemctl restart wazuh-api

# curl -u foo:bar "localhost:55000/experimental/epepe?pretty"
curl: (52) Empty reply from server
```

**Comment by mgmacias95** [comment] 2019-02-18 11:08
Hello @cristgl,

Do you have your API with https configured?

Best regards,
Marta

**Comment by cristgl** [comment] 2019-02-19 07:36
Hi @mgmacias95, yes I did have https configured, I have already checked it. I have tried to send the next request:

```
# curl -u foo:bar "https://localhost:55000/experimental/epepe?pretty"
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by mgmacias95** [comment] 2019-02-19 08:18
Hello @cristgl,

You need to use `-k` option since you're using a self signed certificate. This way `curl` won't try to verify the certificate:

```
# curl -u foo:bar -k "https://localhost:55000/experimental/epepe?pretty"
```

Best regards,
Marta

**Comment by mgmacias95** [comment] 2019-03-27 16:00
Closing this issue since it's been more than a month since the last comment.

**Closed by mgmacias95** 2019-03-27 16:00 UTC

**Comment by cbluth** [comment] 2019-04-29 12:14
> Hello @cristgl,
> 
> You need to use `-k` option since you're using a self signed certificate. This way `curl` won't try to verify the certificate:
> 
> ```
> # curl -u foo:bar -k "https://localhost:55000/experimental/epepe?pretty"
> ```
> Best regards,
> Marta

Thank you for this, this fixed my issue, but the register script still has a bug related to this:

https://raw.githubusercontent.com/wazuh/wazuh-api/3.8/examples/api-register-agent.sh
