### ISSUE TITLE
Wazuh-Python Internal Error: 'module' object has no attribute 'get_nodes'

### ISSUE THREAD

**Issue by ischisler** [wazuh/wazuh-api#120] opened 2018-06-25 17:49 UTC
When I'm trying to connect the ELK stack to the wazuh server I'm getting the following error: 

`{"error":1000,"message":"Wazuh-Python Internal Error: 'module' object has no attribute 'get_nodes'"}`

I've uninstalled and reinstalled the wazuh-api, but that didn't work. I can't find anybody else having this issue either, any help is much appreciated.

**Comment by mgmacias95** [comment] 2018-06-25 18:02
Hello @ischisler,

Which version of Wazuh and which version of the Wazuh API do you have installed?

Best regards,
Marta

**Comment by ischisler** [comment] 2018-06-25 18:13
`$ rpm -qa wazuh-manager`
`wazuh-manager-3.2.2-1.x86_64`

`$ rpm -qa wazuh-api`
`wazuh-api-3.2.2-1.x86_64`

**Comment by ischisler** [comment] 2018-06-25 18:22
I turned on debugging mode for wazuh-api and this is what it says: 

`WazuhAPI 2018-06-25 18:01:42: CMD - STDOUT: 104 bytes
WazuhAPI 2018-06-25 18:01:42: [::ffff:127.0.0.1] GET /agents/ - 200 - error: '1000'.
WazuhAPI 2018-06-25 18:05:42: Sending SIGTERM to CMD - Command: python args:/var/ossec/api/models/wazuh-api.py stdin:{"function":"/agents","arguments":{},"ossec_path":"/var/ossec"}
WazuhAPI 2018-06-25 18:19:34: Exiting... (SIGTERM)
WazuhAPI 2018-06-25 18:19:35: Selected Python binary at 'python'.
WazuhAPI 2018-06-25 18:19:35: Listening on: http://:::55000
WazuhAPI 2018-06-25 18:19:44: ::ffff:127.0.0.1 GET /agents
WazuhAPI 2018-06-25 18:19:44: CMD - Command: python args:/var/ossec/api/models/wazuh-api.py stdin:{"function":"/agents","arguments":{},"ossec_path":"/var/ossec"}
WazuhAPI 2018-06-25 18:19:44: CMD - Exit code: 0
WazuhAPI 2018-06-25 18:19:44: CMD - STDOUT:
---
{"message": "Wazuh-Python Internal Error: 'module' object has no attribute 'get_nodes'", "error": 1000}

---
WazuhAPI 2018-06-25 18:19:44: CMD - STDOUT: 104 bytes
WazuhAPI 2018-06-25 18:19:44: [::ffff:127.0.0.1] GET /agents/ - 200 - error: '1000'.`

**Comment by mgmacias95** [comment] 2018-06-25 18:24
Hello again @ischisler,

I think the error is caused because the function `get_nodes` is not present in your wazuh installation. To check that, do the following:
```
# cat /var/ossec/framework/wazuh/cluster.py | grep get_node
```

If everything is fine, it should show you [the following](https://github.com/wazuh/wazuh/blob/642556ba02f209e0136bc98df749e2bc3b739f03/framework/wazuh/cluster.py#L453):
```python
def get_node(name=None):
```

Best regards,
Marta

**Comment by ischisler** [comment] 2018-06-25 18:36
yes, I get the following: 

`[root@wazuh-server01.prod.us-east-1 ~]$ cat /var/ossec/framework/wazuh/cluster.py | grep get_node`
`def get_nodes(updateDBname=False, config=None):`
               ` response = get_node()`
`def get_node(name=None):`
      `  all_nodes = get_nodes(updateDBname, config)['items']`
   ` local_node = get_node()['node']
`

**Comment by mgmacias95** [comment] 2018-06-25 18:41
Hello @ischisler,

Thank you so much, I see the function is present in your code. 

Then, we're getting the full error trace with the following command:

```shellsession
# echo '{"function":"/agents","arguments":{},"ossec_path":"/var/ossec"}' | /var/ossec/api/models/wazuh-api.py --debug
```

Best regards,
Marta

**Comment by ischisler** [comment] 2018-06-25 18:44
thank you for your help, the following comes back with that command: 
```[root@wazuh-server01.prod.us-east-1 ~]$ echo '{"function":"/agents","arguments":{},"ossec_path":"/var/ossec"}' | /var/ossec/api/models/wazuh-api.py --debug
{"message": "Wazuh-Python Internal Error: 'module' object has no attribute 'get_nodes'", "error": 1000}
Traceback (most recent call last):
  File "/var/ossec/api/models/wazuh-api.py", line 218, in <module>
    '/cluster/nodes': cluster.get_nodes,
AttributeError: 'module' object has no attribute 'get_nodes'
```

**Comment by mgmacias95** [comment] 2018-06-25 19:34
Hello again @ischisler,

Can you post your cluster.py file? The one you have in prod. It would help me a lot to reproduce your issue.

Thanks,
Marta

**Comment by ischisler** [comment] 2018-06-25 19:40
hi @mgmacias95 

one thing I did notice is that staging has a /var/ossec/framwork/wazuh/cluster.py file and prod does not, only the compiled binary cluster.pyc

Not sure if that has anything to do with the issue.

**Comment by mgmacias95** [comment] 2018-06-25 19:42
Hello @ischisler,

There must be a .py file and a .pyc file. 

Try copying your nonprod cluster.py to your prod environment and check if that works.

Best regards,
Marta

**Comment by ischisler** [comment] 2018-06-25 20:14
@mgmacias95 thank you so much for your help. It seemed to be an issue with puppet, in the staging environment we had a entry: 
`package { 'wazuh-manager':
    ensure => '3.2.2-1',
    require => Yumrepo['wazuh'],
  }`


and in prod we had: 

` package { 'wazuh-api':
    ensure => installed,
    require => Yumrepo['wazuh'],
  }`

**Comment by mgmacias95** [comment] 2018-06-25 22:10
Hello @ischisler,

I'm glad your problem got solved! 😄 I'll close this issue but don't hesitate to open a new one if you have new problems.

Best regards,
Marta

**Closed by mgmacias95** 2018-06-25 22:10 UTC
